### ISSUE TITLE
crash: supportsCameraApi: Unknown camera ID 1

### ISSUE THREAD

**Issue by Rakastan** [botyourbusiness/android-camera2-secret-picture-taker#25]
2020-11-24 15:01:10.285 881-1948/? E/CameraService: supportsCameraApi: Unknown camera ID 1
2020-11-24 15:01:10.287 32188-32188/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hzitoun.camera2secretpicturetaker, PID: 32188
    java.lang.IllegalArgumentException: supportsCameraApi:2168: Unknown camera ID 1
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:811)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:333)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:369)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:608)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:536)
        at com.hzitoun.camera2SecretPictureTaker.services.PictureCapturingServiceImpl.openCamera(PictureCapturingServiceImpl.java:118)
        at com.hzitoun.camera2SecretPictureTaker.services.PictureCapturingServiceImpl.startCapturing(PictureCapturingServiceImpl.java:100)
        at com.hzitoun.camera2SecretPictureTaker.activities.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:58)
        at com.hzitoun.camera2SecretPictureTaker.activities.-$$Lambda$MainActivity$P24AwWWVK6x_J4ZWyiyarnYMwY8.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7217)
        at android.view.View.performClickInternal(View.java:7191)
        at android.view.View.access$3500(View.java:828)
        at android.view.View$PerformClick.run(View.java:27679)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: android.os.ServiceSpecificException: supportsCameraApi:2168: Unknown camera ID 1 (code 3)
        at android.os.Parcel.createException(Parcel.java:2085)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.hardware.ICameraService$Stub$Proxy.supportsCameraApi(ICameraService.java:857)
        at android.hardware.camera2.CameraManager.supportsCameraApiLocked(CameraManager.java:864)
        at android.hardware.camera2.CameraManager.supportsCamera2ApiLocked(CameraManager.java:840)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:307)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:369) 
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:608) 
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:536) 
        at com.hzitoun.camera2SecretPictureTaker.services.PictureCapturingServiceImpl.openCamera(PictureCapturingServiceImpl.java:118) 
        at com.hzitoun.camera2SecretPictureTaker.services.PictureCapturingServiceImpl.startCapturing(PictureCapturingServiceImpl.java:100) 
        at com.hzitoun.camera2SecretPictureTaker.activities.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:58) 
        at com.hzitoun.camera2SecretPictureTaker.activities.-$$Lambda$MainActivity$P24AwWWVK6x_J4ZWyiyarnYMwY8.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:7217) 
        at android.view.View.performClickInternal(View.java:7191) 
        at android.view.View.access$3500(View.java:828) 
        at android.view.View$PerformClick.run(View.java:27679) 
        at android.os.Handler.handleCallback(Handler.java:900) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8347) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by burakikanyildiz** [comment]
any update ?
